language: python
python:
  - 3.6
cache:
  directories:
    - web
    - backend
services:
  - postgresql
before_script:
  - psql -c 'create database codeideas;' -U postgres
install:
  - pip install -r requirements.txt
script:
  - cd web && npm install && npm run dev
  - cd ..
  - cd backend && source setup_dev
  - python manage.py runserver localhost:8000