language: python
python:
  - 3.6
cache:
  directories:
    - web
    - backend
services:
  - postgresql
before_script:
  - psql -c 'create database codeideas;' -U postgres
install:
  - cd backend && pip install -r requirements.txt
script:
  - cd .. && ./rFind