language: python
python:
  - 3.6
cache:
  directories:
    - web
    - backend
services:
  - postgresql
before_script:
  - psql -c 'create database codeideas;' -U postgres
install:
  - cd web && npm install
  - cd ../backend && source setup_dev
  - python manage.py runserver localhost:8000
script:
  - cd ../web && npm run dev